name: PR_Build

on: 
  push:
    branches-ignore:
      - 'master'
      - 'beta'
      - 'release-*'

jobs:
  build:
    env:
      Configuration: Release

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup GitHub NuGet Registry (GPR)
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/genexuslabs/index.json" -UserName %GITHUB_ACTOR% -Password ${{ secrets.GITHUB_TOKEN }} 


    - name: Restore packages
      run: |
        $CommitNumber = git rev-list --no-merges --count HEAD

        dotnet restore dotnet\DotNetStandardClasses.sln
        echo "::set-env name=CommitNumber::$CommitNumber"
    - name: Build
      run: |

        dotnet build dotnet\DotNetStandardClasses.sln --no-restore --configuration $Env:Configuration /p:CommitNumber=$Env:CommitNumber
        
    - name: Test
      run: |

        dotnet test dotnet\DotNetStandardClasses.sln --no-restore --no-build --configuration $Env:Configuration /p:CommitNumber=$Env:CommitNumber

    - name: Pack
      run: |

        # Get the FileVersion from the Build.props file
        $GetFileVersionOutput = dotnet msbuild dotnet/Directory.Build.props /t:GetFileVersionForPackage /p:CommitNumber=$Env:CommitNumber
        "$GetFileVersionOutput" -match "(?<=FileVersion:)(.*)"
        $NuGetPackageVersion = $Matches[0] + "-alpha" + $Env:CommitNumber

        dotnet pack dotnet\DotNetStandardClasses.sln --no-restore --no-build --configuration $Env:Configuration /p:Version=$NuGetPackageVersion                